### ISSUE TITLE
Url shortener

### ISSUE THREAD

**Issue by ghost** [BeastImran/all_utility_bot_public_repo#1]
I'm starting on the component of the bot

**Comment by Kelvinamoaba** [comment]
`import pyshorteners
import os 

#An API-KEY would be required for bit.ly
#It can be obtained by visiting their website https://app.bitly.com/
shortener = pyshorteners.Shortener(api_key=os.environ['bitly_key'])

def shorten_link(url):
    """This function will take in the link by the user and then return the shortened version of the 
    link using the bitly service.
    """
    shortened_link = shortener.bitly.short(url)
    return shortened_link

`

**Comment by BeastImran** [comment]
Great, thank you for contributing ❤️. I am adding the feature and updating the repo accordingly soon.

A little suggestion for next time. Just include only the script or the feature component or the project file only. Please do not include the whole environment you have used. It would be far easier for me to review and include the code.

Hope you would continue the work 😄. Sincerely thanking you!

**Comment by BeastImran** [comment]
Done 👍🏻. Take a look at the README and the bot.

**Comment by ghost** [comment]
Thank you to for helping me have this experience.
Would continue to contribute to the project.
Thanks for your advice also.
